"""add_user_id_to_tables

Revision ID: 18584d4b52a4
Revises: d83586eab1be
Create Date: 2025-11-27 19:31:53.252768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18584d4b52a4'
down_revision = 'd83586eab1be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'calendar_events', 'users', ['user_id'], ['id'])
    op.add_column('email_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'email_logs', 'users', ['user_id'], ['id'])
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_column('notes', 'user_id')
    op.drop_constraint(None, 'email_logs', type_='foreignkey')
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_column('email_logs', 'user_id')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'user_id')
    # ### end Alembic commands ###
