"""add_timers_table

Revision ID: 62296d8c69dc
Revises: 18584d4b52a4
Create Date: 2025-11-27 20:07:48.053946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62296d8c69dc'
down_revision = '18584d4b52a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TIMER', 'ALARM', name='timertype'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('trigger_time', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='timerstatus'), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timers_id'), 'timers', ['id'], unique=False)
    op.create_index(op.f('ix_timers_user_id'), 'timers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timers_user_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_id'), table_name='timers')
    op.drop_table('timers')
    # ### end Alembic commands ###
